version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "wiki-scrap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hyn8fotjq3l6"
s3_prefix = "wiki-scrap"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=258553770771.dkr.ecr.us-east-2.amazonaws.com/myecr"]
